language: node_js

node_js:
   - "4.2"

before_install:
  - npm install -g karma mocha karma-mocha karma-mocha-reporter karma-chai-plugins karma-coverage 
  - npm install -g karma-phantomjs-launcher karma-firefox-launcher karma-chrome-launcher 
  - npm install -g browserify karma-browserify

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  npm test


branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - $(npm config get prefix)/bin

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

